name: Snake

# Atualiza o snake a cada 5 horas
on:
  schedule:
    - cron: "0 */5 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Clona o repositório
      - name: Checkout repo
        uses: actions/checkout@v3

      # Gera o snake
      - name: Generate Snake Animation
        uses: Platane/snk@v3
        with:
          github_user_name: LeonardoPires2
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake.gif

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
